version: '3.8'

services:
  fastapi:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    environment:
      # Server
      - "SERVER_HOST=0.0.0.0"
      - "SERVER_PORT=8080"
      - "DB_NAME=ABOBA"
    ports:
      - "8080:8080"
