version: '3.8'

services:
  fastapi:
    build:
      dockerfile: Dockerfile
    restart: always
    environment:
      # Server
      - "SERVER_HOST=0.0.0.0"
      - "SERVER_PORT=8080"
      - "DB_NAME=my_database.db"
      - "AUTH_SECRET_KEY=$AUTH_SECRET_KEY"
      - "AUTH_TOKEN_EXPIRE=15"
      - "AUTH_REFRESH_TOKEN_EXPIRE=60"
    ports:
      - "8080:8080"