name: Python package

on: [push, pull_request]

jobs:
  python:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run tests print
        run: |
          docker images
