name: Python package

on: [push, pull_request]

jobs:
  python:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          docker compose build
      - name: Run images
        run: |
          docker compose up
