name: Python package

on: [push, pull_request]

jobs:
  python:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build and run Docker Compose
        run: |
          docker-compose up --build -d
